source 'https://rubygems.org'

gem 'rails', '~> 7.0.0'
gem 'pg', '~> 1.4'
gem 'redis', '~> 5.0'
gem 'devise', '~> 4.8'
gem 'jwt', '~> 2.5'
gem 'dotenv-rails', groups: [:development, :test]

group :development, :test do
  gem 'rspec-rails', '~> 6.0'
  gem 'factory_bot_rails', '~> 6.2'
  gem 'faker', '~> 3.2'
end

group :production do
  gem 'puma', '~> 6.0'
end 