global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'api-gateway'
    static_configs:
      - targets: ['api-gateway:3000']

  - job_name: 'auth-service'
    static_configs:
      - targets: ['auth-service:3001']

  - job_name: 'product-service'
    static_configs:
      - targets: ['product-service:4000']

  - job_name: 'cart-service'
    static_configs:
      - targets: ['cart-service:3002']

  - job_name: 'payment-service'
    static_configs:
      - targets: ['payment-service:8000']

  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100'] 